# Generated by Django 5.1.6 on 2025-02-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist_app', '0003_editorial_remove_book_active_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='editorial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='booklist_app.editorial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editorial',
            name='description',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editorial',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
