# Generated by Django 5.1.6 on 2025-02-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist_app', '0004_book_author_book_created_book_editorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='description',
        ),
    ]
